version: '3.7'
services:
    hackit:
        build: hackIT
        environment:
            - GAMMA_CLIENT_ID=id
            - GAMMA_CLIENT_SECRET=secret
            - GAMMA_AUTH_URL=http://localhost:8081/api/oauth/authorize
            - GAMMA_TOKEN_URL=http://gamma-backend:8081/api/oauth/token
        ports:
            - 8000:8000
        volumes:
            - /usr/src/app/target
            - ./hackIT:/usr/src/app
        networks:
            - hackit
            - gamma
        
    postgresql: 
        image: postgres:12.3-alpine
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
        networks:
            - hackit

    adminer:
        image: adminer
        ports:
            - 8080:8080
        depends_on:
            - postgresql
        networks:
            - hackit

    gotify:
        image: cthit/gotify:latest
        environment:
            GOTIFY_PRE-SHARED-KEY: 123abc
            GOTIFY_MOCK-MODE: "true"
            GOTIFY_DEBUG-MODE: "true"
        ports:
            - 1337:8080
        networks:
            - gamma

    gamma-frontend:
        image: cthit/gamma-frontend:development
        environment:
            HTTP_PROXY: http://gamma-backend:8081
        depends_on:
            - gamma-backend
        networks:
            - gamma
        ports:
            - 3000:3000

    gamma-backend:
        image: cthit/gamma-backend
        environment:
            # Default admin user name = admin
            # Default admin password  = password
            DB_USER: user
            DB_PASSWORD: password
            DB_HOST: gamma-db
            DB_PORT: 5432
            DB_NAME: postgres

            REDIS_HOST: gamma-redis
            REDIS_PASSWORD: ""
            REDIS_PORT: 6379

            GOTIFY_KEY: "123abc"
            GOTIFY_URL: http://gamma-gotify:8080/mail

            DEFAULT_CLIENT_NAME: demo
            DEFAULT_CLIENT_ID: id
            DEFAULT_CLIENT_SECRET: secret
            DEFAULT_REDIRECT_URI: http://localhost:8000/auth/gamma

            SERVER_PORT: 8081
            SUCCESSFUL_LOGIN: http://localhost:5555
            CORS_ALLOWED_ORIGIN: http://localhost:5555
            BACKEND_URI: http://localhost:8081
            PRODUCTION: "false"
            COOKIE_DOMAIN: localhost
            IS_MOCKING_CLIENT: "true"
        depends_on:
            - gamma-redis
            - gamma-db
        networks:
            - gamma
        ports:
            - 8081:8081

    gamma-redis:
        image: redis:5.0
        networks:
            - gamma

    gamma-db:
        image: postgres:10
        environment:
            POSTGRES_USER: user
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: password
        networks:
            - gamma

networks:
    hackit:
    gamma:
