version: '2'
services:
  hackit:
    build:
        context: ./hackIT
        dockerfile: prod.Dockerfile
    environment:
      DATABASE_URL: postgres://user:pass@postgresql/hackit
      ROCKET_DATABASES: '{hackit={url="postgres://user:pass@postgresql/hackit"}}'
    ports:
        - 8000:8000
    
  postgresql:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_DB: hackit
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
    volumes:
    - /var/lib/postgresql/data