id = "qckmath"
lvl = 1
name = "Teacher smurf needs assistance!"
desc = '''
School is starting in smurf village, but due to frequent cat attacks there are a lack of teachers!
Teacher smurf wants to teach students to magic of the fibonacii series, but is too busy grading 6 other classes...
Can you help teacher smurf?
'''
spec = '''
The nth fibonacci number is defined as:
    F(0) = 0
    F(1) = 1
    F(n) = F(n-1) + F(n-2)

Given an interger n, your program must return the nth fibonacci number
example:
    (input)
    8
    (output)
    21
'''
scen = [
    ["1q.txt","1a.txt"],
    ["2q.txt","2a.txt"],
    ["3q.txt","3a.txt"],
    ["4q.txt","4a.txt"],
    ["5q.txt","5a.txt"],
    ["6q.txt","6a.txt"],
    ["7q.txt","7a.txt"],
    ["8q.txt","8a.txt"],
    ["9q.txt","9a.txt"],   
]