id = "flask"
lvl = 3
name = "Alchemy is the art of inequivalent exchange"
desc = '''
Times are rough for alchemist smurf.

His latest round of experiments have failed to show results
and his main investor (gullible smurf) is starting to
doubt that one can convert apples to smurf gold...

However all is not lost! After serveral nights of inhaling
toxic fumes, and a pinch of sleep deprivation, he has finaly
cracked the code to not only transmutation of smurf gold
but to imortaility itself!

There is one catch.

He only has a couple of potions and cans of fuel left.
This means he has devies a plan to transmute his inventory
to the ingredients he needs in as few steps as possible to
avoid running out of fuel.

this is where you come in!
'''
spec = '''
In smurf alchemy there are 4 main ingredients:
    (R)ed potion,
    (G)reen potion,
    (B)lue potion,
    (Y)ellow Potion

These potions can be transmuted to other potions according to these rules:
    R -> G + B
    G -> B
    B -> G
    B -> 2R
    R + G -> Y
    R + Y -> 2B
    G + B -> 3R

To acheive imortality, Alchemist smurf needs the ingerdients:
    2R, 3G, 2B, and 4Y

Your goal is to find the least amount of steps needed to transmute alchemist smurf's inventory to the
ingredients needed.

the answer is the amount of steps needed

example:
    (input)
    1R 1G 1B 0Y
    (output)
    18
    '''
scen = [
    ["1q.txt","1a.txt"],
    ["2q.txt","2a.txt"],
    ["3q.txt","3a.txt"],
    ["4q.txt","4a.txt"],
    ["5q.txt","5a.txt"],
    ["6q.txt","6a.txt"],
    ["7q.txt","7a.txt"],
    ["8q.txt","8a.txt"],
    ["9q.txt","9a.txt"],   
]

