id = "bugz"
lvl = 1
name = "Too many bugs to count!"
desc = '''
Disaster in entomologist smurfs labrotory!

A large amount of toxic insects broke out of their
enclousers, threating the neighbouring preschool!

Thankfuly the smurfs acted fast and captured all
of the bugs in one large bucket.

But did they realy capture all of them? Help the smurfs
write a program to check!
''' 
spec = '''
There are four species of insects to count:
    Bullet (A)nts
    (G)iant Japanese Hornets
    Deathstalker S(C)orpion
    Sri Lanka Ornamental (T)arantula

Given a newline seperated list of letters
find the total of each speicies in the format
An,Cn,Gn,Tn where "n" is an integer 
example:
    (input)
    A
    C
    C
    G
    A
    (output)
    A2,C2,G1,T0
'''
scen = [
    ["1q.txt","1a.txt"],
    ["2q.txt","2a.txt"],
    ["3q.txt","3a.txt"],
    ["4q.txt","4a.txt"],
    ["5q.txt","5a.txt"],
    ["6q.txt","6a.txt"],
    ["7q.txt","7a.txt"],
    ["8q.txt","8a.txt"],
    ["9q.txt","9a.txt"],
]

