id = "ledger"
lvl = 2
name = "Accountant smurfs dilema"
desc = '''
Good news: The annual smurf bar-crawl was a huge success!
Bad news: the smurf village is now in ruins...
Pappa smurf has asked accountant smurf to check if the procceds from the bars covers the damage claims, but accountant smurf is still hungover from the pub-crawl!
Can you build a program to save accountant smurf? 
    '''
spec = '''
Given a newline terminated list of transactions, calculate the net sum.
transactions defined by a "sign" folowed by a whole number
where the sign dictates wether the transaction is income or cost.

example:
    (input)
    +503
    -324
    +200
    (output)
    379
    '''
scen = [
    ["1q.txt","1a.txt"],
    ["2q.txt","2a.txt"],
    ["3q.txt","3a.txt"],
    ["4q.txt","4a.txt"],
    ["5q.txt","5a.txt"],
    ["6q.txt","6a.txt"],
    ["7q.txt","7a.txt"],
    ["8q.txt","8a.txt"],
    ["9q.txt","9a.txt"],   

]

